### ISSUE TITLE
Bug? installer > alte Version wird noch als update angezeigt

### ISSUE THREAD

**Issue by madiko** [wende60/myevents#12]
Hallo Joachim,

ich installierte in meinem Testsystem Dein AddOn myevents und nahm über den Installer das update auf 2.1.12beta vor. Im installer wird mir jedoch weiterhin das (veraltete) update auf V2.1.111 (noch mit textile) angeboten. Kannst Du Dir darauf einen Reim machen?

Werde das AddOn testen und Dir dann gern noch mal Feedback dazu geben. 

Besten Dank und viele Grüße,
Franziska

**Comment by wende60** [comment]
Servus Franziska,

kann sein, dass ich hier schlampig war, musste mir erst einen API key besorgen ;)
Probier bitte nochmal. Es sollte die verfügbare Version 2.2.1 angezeigt werden. Diese wird als Voraussetzung Markitup erwarten.

Grüsse, Joachim

**Comment by madiko** [comment]
Hallo Joachim,

super, jetzt klappt es. Vielen Dank für die superschnelle Antwort! :-)

Noch ein Tipp für die Doku, weil ich es auch nicht gleich geblickt habe: 
Du schreibst unter "Module erstellen", dass es im Ordner "examples" Beispiele gibt. Am besten verlinkst Du diesen Ordner hier zu git. Ich suchte ihn zuerst im Ordner-Verzeichnis vom AddOn. So machst Du es Newbies einfacher. ;-)

Nochmals besten Dank.
Franziska

**Comment by wende60** [comment]
done :)
Danke fürs Feedback, 

Grüsse, Jo
