### ISSUE TITLE
 [Sicherheit] - SQL Injection in MyEvents Backend

### ISSUE THREAD

**Issue by olien** [wende60/myevents#14]
Hallo Joachim,

guck doch mal bitte hier: https://redaxo.org/forum/addons-packages-r5-f43/sicherheit-sql-injection-in-myevents-backend-t22128.html

LG
Oliver

**Comment by wende60** [comment]
danke für den Hinweis. Muss dann am Wochenende nochmal durch alle Dateien gehen...

**Comment by wende60** [comment]
merged...
