### ISSUE TITLE
Kategorien

### ISSUE THREAD

**Issue by TrueHatori** [wende60/myevents#2]
Zunächst mal danke, tolles AddOn.
Meine Frage: Könnte man vielleicht noch Kategorien einfügen? Für den ursprünglichen Zweck waren die sicherlich nicht erforderlich, aber jetzt würde es schon Sinn machen.
Z.B. hier: [http://www.ninja4ever.de/index.php?article_id=110](http://www.ninja4ever.de/index.php?article_id=110)
Im Moment sind da nur Dojo-interne Events drin, wenn aber andere Seminare, Festivals oder was auch immer für Events dazu kommen, wird es schnell unübersichtlich.
Es würde völlig ausreichen, wenn man vor den Event-Titel oder das Datum ein Symbol setzen könnte, eine spezielle Auflistung der Kategorien tut gar nicht Not. Nur eben soviel, dass man die Kategorien unterscheiden kann.

**Comment by wende60** [comment]
Bitte gerne ;)

Kategorien wären sicher eine gute Idee, werde ich mal in die Todos aufnehmen. Ich glaube, ich habe eh ein unbenutztes Feld, so dass man einfach einen Freitext reinschreiben könnte. Besser wäre natürlich, Kategorien anlegen zu können, und auch danach filtern zu können. 
Du könntest in der Zwischenzeit natürlich auch einfach das Ortsfeld missbrauchen, den Ort kann man ja auch in der Beschreibung mit aufnehmen...

Grüsse, Jo

**Comment by TrueHatori** [comment]
Sorry, war ein paar Tage nicht da.
Das hört sich gut an. Das Ortsfeld werde ich besser nicht "missbrauchen", dann muss ich ja alles umschreiben, wenn ein Update kommt ;) Für den Moment bin ich zufrieden mit dem, was ich habe. Hab es optisch noch ein wenig verbessert, so gehts erstmal.
Noch ein kleiner Hinweis: Wenn man einen neuen Termin gespeichert hat (im Backend), gibt es doch unten die zwei Links "zurück zu MyEvents" und "neuen Event anlegen". Da ist der Link durchgehend und führt immer auf event_add. Ich benutze eh oben die Tabs, ist daher für mich nicht das Problem, ein kleiner Schönheitsfehler ;)

**Comment by wende60** [comment]
hi, im neuesten master findest Du nun ein zusätzliches Eingabefeld, dass in myevents_content -> addcontent geschrieben wird. Dort könntest Du also auch Kategorien eintragen. Die Beispiele habe ich entsprechend upgedatet. Das unten ist übrigens nur _ein_ Link ;)
Grüsse, jo
