### ISSUE TITLE
Kalender wird nicht angezeigt

### ISSUE THREAD

**Issue by casibo** [wende60/myevents#5]
Hallo, bei meinen HP wird leider der Kalender nicht angezeigt. 
Version
REDAXO5.2.0
PHP7.0.9

Seite liegt bei one.com
Lokal ist der Kalender zu sehen

![image](https://cloud.githubusercontent.com/assets/7475085/17275556/7d3d65ee-570c-11e6-9844-f7546188552b.png)

**Comment by wende60** [comment]
Welchen Browser verwendest Du? Welche Fehler zeigt die Konsole? Das PHP spielt keine Rolle, der Kalender wird mit Javascript generiert.

**Comment by casibo** [comment]
Habe es schon in Chrome, Firefox, IE und in allem wird es nicht angezeigt:

Fehlermeldung: 
![image](https://cloud.githubusercontent.com/assets/7475085/17306140/a86f4fb6-582e-11e6-9c29-70a9f824eeb9.png)

**Comment by wende60** [comment]
Wenn Redaxo ein Addon installiert werden alle Inhalte im Addon unter "assets" nach /assets/addons/[addonname]/ kopiert. Du bekommst jedoch einen 404 beim Aufruf von http://www.lida1862.de/assets/addons/myevents/myevents.js. Das ist also nicht wirklich ein Addon-Problem, sieht eher nach einem Setup-Problem aus.

Bitte prüfe die Rechte der übergeordneten Verzeichnisse: '/assests/addons' - Redaxo muss da Schreibrechte haben - und reinstalliere das Addon dann nochmal. Prüfe anschliessend, ob alle Dateien entsprechend angelegt wurden. 

Ggf kannst Du die Dateien auch manuell nach /assets/addons/myevents kopieren.

**Comment by casibo** [comment]
habe es nun gemacht, jetzt hab ich ein Srciptfehler: 
![image](https://cloud.githubusercontent.com/assets/7475085/17338325/51da44bc-58e7-11e6-816f-a999783a1512.png)

**Comment by wende60** [comment]
hm, das kann ich leider nicht nachvollziehen, insbesondere auch weil 
**firstDayOfMonth = currentDates[0].dplDay,**
garnicht in Zeile 209 steht. Seltsam ist auch, dass dieser Fehler bereits im ersten Screenshot zu sehen ist, ohne dass die Datei dort ja überhaupt geladen wird, weil ja ein 404 auftritt. Irgenwas ist da schräg, per Ferndiagnose kann ich Dir leider nicht weiterhelfen.
